### ISSUE TITLE
Hicada to HTML String ?

### ISSUE THREAD

**Issue by DjebbZ** [rauhs/hicada#1]
Hello,

It seems like Hicada is useful to compile Hiccup-like syntax to Javascript code for React.js-like libraries. What do you think about having it compile to HTML directly so it can be used server side ?

**Comment by rauhs** [comment]
I thought about this yesterday. I'm not going to get into the business of writing another implementation that outputs the string. IMO the best/fastest server side render is rum. So I just landed support for this with a new config option:

```clj
(rum-render/render-html
    (hicada/compile [:div {:style {:color "blue"}} "x"
                     [:span "foo"]]
                    {:server-render? true
                     :emit-fn (fn [tag attr children]
                                (into [tag attr] children))}))
```

Outputs:

```html
"<div style=\"color:blue;\" data-reactroot=\"\" data-reactid=\"1\" data-react-checksum=\"282865149\"><!-- react-text: 2 -->x<!-- /react-text --><span data-reactid=\"3\">foo</span></div>"
```

Not really tested all that much so expect some rough edges.

**Comment by DjebbZ** [comment]
Makes sense, even if nothing prevents you to "steal" rum code if you really wanted to, haha.

Keep up the good work !
