### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by g7s** [rauhs/hicada#16]
I have been playing with the `:server-side?` option of hicada and I stumbled upon a weird behavior. Right now hicada uses `compile-config` to change the HTML attributes of an element to a camelCase version (among other things).

1. The hardcoded conversion `:class -> :className` and `:for -> :htmlFor` only makes sense for React
2. `:style` attribute keys get converted to camelCase even though I specified `:camelcase-key-pred` to be `(constantly false)`.

The solution I propose is: when we `:server-render?` any kind of attribute conversion should be delegated to the library that does the SSR and not by hicada. That means that joining the classes and camelCasing the style keys are decisions that should be made by the SSR library.

```diff
diff --git a/src/hicada/compiler.clj b/src/hicada/compiler.clj
index 513015f..6af65de 100644
--- a/src/hicada/compiler.clj
+++ b/src/hicada/compiler.clj
@@ -379,7 +379,7 @@
   "Emits the final react js code"
   [tag attrs children]
   (let [{:keys [transform-fn emit-fn inline? wrap-input?
-                create-element array-children?]} *config*
+                create-element array-children? server-render?]} *config*
         [tag attrs children] (transform-fn [tag attrs children *env*])]
     (if inline?
       (let [type (or (and wrap-input? (util/controlled-input-class tag attrs))
@@ -405,7 +405,7 @@
                    wrapper-class
                    (tag->el tag))
                  (tag->el tag))
-            cfg (to-js (compile-config attrs))]
+            cfg (if server-render? attrs (to-js (compile-config attrs)))]
         (if emit-fn
           (emit-fn el cfg children)
           (apply list create-element el cfg children))))))
```

What do you think?

**Comment by rauhs** [comment]
PR welcome
