### ISSUE TITLE
Deploy a new version (> 0.1.8)

### ISSUE THREAD

**Issue by lambdam** [rauhs/hicada#19]
Hello,

I'm trying hicada on a toy project and on this form:
```cljs
(defn footer [props]
  ...)

(el/html
  [:> footer])
```
I get the following error: `clojure.lang.ArityException: Wrong number of args (0) passed to: hicada.compiler/fn--24353`

This comes from the fact that on 0.1.8, the handler function for `:>` still doesn't handle this arity but it does on master.
0.1.8: https://github.com/rauhs/hicada/blob/555db38001deb36656e21d9eecd6483464455bb7/src/hicada/compiler.clj#L20-L21
master: https://github.com/rauhs/hicada/blob/90994bd09ba035735f4028074cae516a1948bdd0/src/hicada/compiler.clj#L20-L26

That would be nice to have a 0.1.9 version.

Thanks a lot

**Comment by rauhs** [comment]
Sorry for the delay, not doing any Clojure stuff nowadays so I had to re-setup java/lein/clojars. Just pushed the new 0.19.
