### ISSUE TITLE
trouble compiling project

### ISSUE THREAD

**Issue by hoebat** [rauhs/hicada#4]
I'm really impressed with the library. It's super clean and the examples look great.

However, when I do `lein figwheel` this happens:

<img width="500" alt="screen shot 2018-06-29 at 3 42 27 pm" src="https://user-images.githubusercontent.com/1455572/42079832-5b6baf66-7bb3-11e8-9ef4-d856968b6f0d.png">

**Comment by rauhs** [comment]
Can you tell me more about your setup? Is that a `lein figwheel` in hicada? I'm not sure anything is setup here. Or is that an error after you started using hicada?

**Comment by hoebat** [comment]
i just cloned hicada and ran `lein figwheel`. Some files are missing.

**Comment by rauhs** [comment]
Don't do that. It's not supported. I develop the lib in a different way here locally.
