### ISSUE TITLE
Private discussion

### ISSUE THREAD

**Issue by lynaghk** [rauhs/hicada#7]
Hi @rauhs, I have a fork of Hicada that includes an interpreter and uses cljs type inference to reduce overhead. I'd love to privately discuss merging upstream and get your feedback.

If you're interested, please email me: kevin@keminglabs.com
I plan to blog about my work in a week, and would love to hear from you before then.
In any event, thanks for your work on Hicada. It's great!

**Comment by rauhs** [comment]
Connected
